#!/bin/bash
ls -Ap | awk "BEGIN{ORS=\",\"} {if (\$0 ~ /\\/$/) printf \"%s/,\", \$0; else printf \"%s,\", \$0} END{print \"\"}" | sort -d -k1 | awk "{if (\$0 ~ /^(\\.\\.?|[^.].*)\//) printf \"%s,\", \$0; else printf \"%s\", \$0}"
